[env:nucleo_f446re]
platform = ststm32
board = nucleo_f446re
framework = stm32cube
monitor_speed = 115200

; Configurações do Monitor Serial
monitor_port = COM3  ; <-- Troque pelo número da porta que aparece no seu gerenciador
monitor_filters = direct
monitor_echo = yes